version: '3'

services:
  tasksDb:
    image: postgres:15.3
    container_name: tasks-db
    ports:
      - 5432:5432    
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data