import { ProductsListClient } from "@/src/products";
import { Metadata } from "next";

export default async function ClientSidePage() {


    return (
        <>
            <h1 className="mb-5">Productos - Client Side Rendering</h1>
            <ProductsListClient/>
        </>
    );
}


export const metadata: Metadata = {
    title: 'Client Side Rendering',
    description: 'Generated by create next app',
}