import type { Metadata } from 'next'
import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import { authOptions } from '../api/auth/[...nextauth]/route';

export const metadata: Metadata = {
  title: 'Login | Innova Dashboard',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  const session = await getServerSession(authOptions);
  
  if (session) {
      redirect('/');
  }

  return (
    <html lang="es">
        <body>
          {children}
        </body>
    </html>
  )
}
