import { SideMenu } from '@/src/components'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { BottomNavigation } from '@/src/components/BottomNavigation'
import { redirect } from 'next/navigation'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {


  const session = await getServerSession(authOptions);

  if( !session ){
      redirect('/api/auth/signin');
  } 


  return (
    <html lang="en">
      <body className={`${nunito.className} flex flex-col md:flex-row relative`}>
        <SideMenu/>
        <main className='w-full md:w-9/12 lg:w-10/12  h-screen md:overflow-y-scroll p-10'>
          {children}
        </main>
        <BottomNavigation/>
      </body>
    </html>
  )
}
