import { SideMenu } from '@/src/components'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} flex flex-col md:flex-row`}>
        <SideMenu/>
        <main className='w-full md:w-10/12 max-h-screen h-screen overflow-y-scroll p-10'>
          {children}
        </main>
      </body>
    </html>
  )
}
