// Generated by https://quicktype.io

export interface Task {
    id:          string;
    title:       string;
    description: string;
    complete:    boolean;
    createdAt:   string;
    updateddAt:  string;
}
